name: Continuous integration Delivery and deployment with github action dotnet 10

on:
  push:
    branches: [ "section30" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Create SQL Server Container
      run: |
        docker run -d --name sqlserver_test \
          -e "ACCEPT_EULA=Y" \
          -e "MSSQL_SA_PASSWORD=Admin123456" \
          -p 1433:1433 \
          mcr.microsoft.com/mssql/server:2022-latest
        
         sleep 10

        timeout 90s bash -c "until docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "Admin123456" -Q 'SELECT 1' -C; do sleep 5; done"

    - name: Create SQL Server Database
      run: docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Admin123456' -Q "IF DB_ID('asp_net_10_erudio') IS NULL CREATE DATABASE [asp_net_10_erudio]" -C
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore PrimeiroProjeto.slnx
      working-directory: asp-net/PrimeiroProjeto

    - name: Build ASP.NET 10 App
      run: dotnet build PrimeiroProjeto.slnx --configuration Release --no-restore
      working-directory: asp-net/PrimeiroProjeto


    - name: Test ASP.NET 10 App
      run: dotnet test PrimeiroProjeto.slnx --configuration Release --no-build --logger "console;verbosity=detailed"
      working-directory: asp-net/PrimeiroProjeto

    - name: Docker Compose Build
      run: docker compose build
      working-directory: asp-net/PrimeiroProjeto

    - name: Push to Docker Hub Container Registry
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/primeiro-projeto:latest -t ${{ secrets.DOCKER_USERNAME }}/primeiro-projeto:${{ github.run_id }} -f asp-net/PrimeiroProjeto/PrimeiroProjeto/Dockerfile .

        docker push ${{ secrets.DOCKER_USERNAME }}/primeiro-projeto:latest

        docker push ${{ secrets.DOCKER_USERNAME }}/primeiro-projeto:${{github.run_id}}

      


