name: Continuous integration Delivery and deployment with github action dotnet 10

on:
  push:
    branches: [ "section30" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
